### Users create (signup)
POST http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzUwMTYzNjV9.wFx1ktrqRAUzgEuVAcordkX_f_ck3JoVtZfvWNkGMqg
Content-Type: application/json

{
  "name": "Joe",
  "email": "joe@example.com",
  "password": "joegreen",
  "password_confirmation": "joegreen"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

### User creates a Dog
POST http://localhost:3000/dogs.json
Authorization: bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzUwMTYzNjV9.wFx1ktrqRAUzgEuVAcordkX_f_ck3JoVtZfvWNkGMqg
Content-Type: application/json 

{
  "name": "Buddy",
  "age": "5",
  "Breed": "Husky"
}